### ISSUE TITLE
[OLD] Legacy German Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/de.react.dev#1]
## Maintainer List

* @ChrisB9
* @ph1p
* @miku86

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR.

Example:
* [x] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@miku86) #5 
* [ ] Tutorial (@ChrisB9, @liza-kl) #174 #34

### Basics

* [x] Hello World (@ph1p) #3 
* [x] Introducing JSX (@ChrisB9 ) #7
* [x] Rendering Elements (@ph1p) #8
* [x] Components and Props (@ph1p) #14
* [x] State and Lifecycle (@ph1p) #28
* [x] Handling Events (@ph1p) #17
* [x] Conditional Rendering (@jahe) #21 
* [x] Lists and Keys (@ph1p) #55 
* [x] Forms (@ph1p) #61 
* [x] Lifting State Up (@codejet) #36 
* [x] Composition vs Inheritance (@codejet) #30 
* [x] Thinking in React (@miku86) #50 

### API Reference

* [x] React (@damienxy) #38 
* [ ] React.Component (@iamstiil, @ph1p) #43 #138 
* [x] ReactDOM (@do-wa) #45 #127
* [x] ReactDOMServer (@damienxy) #39
* [x] DOM Elements (@fnoah) #37 
* [x] SyntheticEvent (@rwachtler) #79
* [x] Test Utilities (@damienxy) #46
* [x] Shallow Renderer (@tamarau) #58 
* [x] Test Renderer (@tamarau) #65 
* [x] JS Environment Requirements (@ph1p) #12 
* [x] Glossary (@ph1p) #63 
* [x] Test-Environments (@michael-schantin)  #292
* [x]  Test-Recipes (@michael-schantin) #294 

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@ChrisB9) #13
* [x] docs/nav.yml (@ph1p) #33 

## Next Steps

These are the next most important translations, ordered by importance:

### InstallationF

* [x] Getting Started (@ph1p) #9
* [x] Add React to a Website (@JohannesKlauss) #27 
* [x] Create a New React App (@JohannesKlauss) #31 
* [x] CDN Links (@ph1p) #2

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@markus-willems) #40
  * [ ] Hooks at a Glance (@rwachtler)
  * [x] Using the State Hook (@tchalabi) #142
  * [ ] Using the Effect Hook (@@vincentrohde)
  * [x] Rules of Hooks (@saraphinaboe) #49 
  * [x] Building Your Own Hooks (@timidak) #168
  * [x] Hooks API Reference (@PReichetanz)
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] dont-call-proptypes (@tamarau) #77 
* [x] invalid-aria-prop (@michaelneu) #94
* [x] invalid-hook-call-warning (@michaelneu) #96
* [x] legacy-factories (@michaelneu) #98
* [x] refs-must-have-owner (@wogsland) #112
* [x] special-props (@michaelneu) #95
* [x] unknown-prop (@wogsland) #111

### Advanced Guides

* [x] Accessibility (@r3sMetz) #60 
* [x] Code-Splitting (@ph1p) #91
* [x] Context (@tamarau) #93 
* [x] Error Boundaries (@rwachtler) #108
* [x] Forwarding Refs (@rwachtler) #110 
* [x] Fragments (@ph1p) #54 
* [x] Higher-Order Components (@rwachtler) #140
* [x] Integrating with Other Libraries (@wogsland) #124
* [x] JSX In Depth (@r3sMetz) #137
* [x] Optimizing Performance (@damienxy) #44
* [x] Portals (@Tamiira) #121 
* [x] React Without ES6 (@amelieoller) #105
* [x] React Without JSX (@janmenzel) #68 
* [x] Reconciliation (@codejet) #70 
* [x] Refs and the DOM (@wogsland) #122
* [x] Render Props (@timhoffmannGIThub) #120 #144
* [x] Static Type Checking (@ph1p) #141
* [x] Strict Mode (@codejet) #131 
* [x] Typechecking With PropTypes (@ZweiDM) #113 
* [x] Uncontrolled Components (@amelieoller) #103 
* [x] Web Components (@ph1p) #35
* [x] Profiler API (@michael-schantin) #300 

### FAQ

* [x] APIs and AJAX (@mhienle) #115
* [x] Babel, JSX, and Build Steps (@mhienle) #99 
* [x] Passing Functions to Components (@pmaier983)
* [x] Component State (@mhienle) #101 
* [x] Styling and CSS (@mhienle)
* [x] File Structure (@amelieoller) #102 
* [ ] Versioning Policy (@mnlfischer)
* [x] Virtual DOM and Internals (@mhienle) #100 

### Contributing

Priority: Low

* [x] How to Contribute @Serag114 #249 
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by jahe** [comment]
Hi! I'd like to translate the Conditional Rendering page.

**Comment by ChrisB9** [comment]
@jahe thank you, i'm excited to see your pull request soon

**Comment by jahe** [comment]
Hi @ChrisB9 @ph1p @miku86!
I'm interested in becoming a maintainer of this repo.
Do you mind if I add a PR to the maintainer list in the `de.json` file of the reactjs/reactjs.org-translation repo?

**Comment by ph1p** [comment]
Nice to hear! Looking forward to your fist PR. @tesseralis can you add him?

**Comment by pke** [comment]
I'd work on "Lists and keys" to move this translation effort forward

**Comment by JohannesKlauss** [comment]
I'd like to translate "Add React to a Website".

**Comment by ph1p** [comment]
I've added you (:

**Comment by miku86** [comment]
> I'd work on "Lists and keys" to move this translation effort forward

 @pke I added you, thanks!

**Comment by codejet** [comment]
I can take "Composition vs Inheritance"

**Comment by ph1p** [comment]
> I can take "Composition vs Inheritance"

Cool ;) added you

**Comment by markus-willems** [comment]
Hey, I would like to help translating Hooks.

Therefore, I would like to claim the intro chapter: https://reactjs.org/docs/hooks-intro.html

**Comment by JohannesKlauss** [comment]
I would also like to translate the "Create a New React App" page.

**Comment by JohannesKlauss** [comment]
I would also like to translate the "Forms" page.

**Comment by fnoah** [comment]
I'd like to translate the "DOM Elements" API reference page.

**Comment by codejet** [comment]
Now I could take "Lifting State Up". Then the basics would be covered.

**Comment by JanBussieck** [comment]
I would like to help translating the Hooks section, as well, starting with https://reactjs.org/docs/hooks-overview.html

**Comment by ChrisB9** [comment]
@JanBussieck thank you for your contribution - i added you

**Comment by damienxy** [comment]
I would like to translate https://reactjs.org/docs/react-api.html

**Comment by ChrisB9** [comment]
@damienxy added you, thank you :)

**Comment by damienxy** [comment]
I would like to take this one next: https://reactjs.org/docs/react-dom-server.html

**Comment by damienxy** [comment]
Next one: https://reactjs.org/docs/optimizing-performance.html
(I know this is in the 'Next Steps' section but I'm really interested in the topic :-))

**Comment by markus-willems** [comment]
I created a PR for the Hooks intro chapter and could start working on the next text. I'd like to claim: https://reactjs.org/docs/hooks-state.html

**Comment by saraphinaboe** [comment]
I would like to contribute by translating https://reactjs.org/docs/hooks-rules.html

**Comment by do-wa** [comment]
I'd like to start translating [ReactDOM](https://reactjs.org/docs/react-dom.html)

**Comment by ph1p** [comment]
added you @do-wa

**Comment by ph1p** [comment]
Added you too, @saraphinaboe

**Comment by damienxy** [comment]
I'd like to take this one next: https://reactjs.org/docs/test-utils.html

**Comment by rwachtler** [comment]
Hello! I'd like to translate [SyntheticEvent](https://reactjs.org/docs/events.html)

**Comment by ph1p** [comment]
> Hello! I'd like to translate [SyntheticEvent](https://reactjs.org/docs/events.html)

Cool! Added you ;)

**Comment by saraphinaboe** [comment]
I'd like to continue with  https://reactjs.org/docs/hooks-effect.html

**Comment by bsotodo** [comment]
I'd like to help with https://de.reactjs.org/docs/hooks-custom.html

**Comment by ph1p** [comment]
> I'd like to help with https://de.reactjs.org/docs/hooks-custom.html

Added you ;)

**Comment by MeiKatz** [comment]
I would like to help with https://de.reactjs.org/docs/hooks-reference.html

**Comment by miku86** [comment]
> I would like to help with https://de.reactjs.org/docs/hooks-reference.html

Thanks for your help, I added you.

**Comment by mwolski89** [comment]
Hey guys, I want to help too! I'm going to translate https://de.reactjs.org/docs/hooks-faq.html!

**Comment by ph1p** [comment]
> Hey guys, I want to help too! I'm going to translate https://de.reactjs.org/docs/hooks-faq.html!

Cool ;) Simply fork this repo and create PR

**Comment by tamarau** [comment]
I would like to translate https://de.reactjs.org/docs/shallow-renderer.html please! :)

**Comment by ph1p** [comment]
Cool ;) Added you @tamarau

**Comment by r3sMetz** [comment]
Hey there, may i start contribitung with translating https://de.reactjs.org/docs/accessibility.html ?

**Comment by ph1p** [comment]
Sure @r3sMetz (: once you've translated a little, please create a PR. This will make it easier to keep track of what topics are currently being worked on.

**Comment by ph1p** [comment]
Oh you're right! ☺️ I corrected it and added you to "Test Renderer"

**Comment by JohannesKlauss** [comment]
Pls free up the Forms section, since I just don't find any time to translate it. Thank you.

**Comment by ph1p** [comment]
Done @JohannesKlauss

**Comment by miku86** [comment]
> Pls free up the Forms section, since I just don't find any time to translate it. Thank you.

But nevertheless thank you very much for having volunteered for this task, even if you couldn't make it :)
If you've done a small part, you can still push it.

**Comment by ph1p** [comment]
> I'd work on "Lists and keys" to move this translation effort forward

I've translated the page @pke, because there was no action since 3 months

**Comment by janmenzel** [comment]
I would like to translate "React Without JSX".

**Comment by ph1p** [comment]
> I would like to translate "React Without JSX".

Cool (: I'll add you. Could you please open a PR after your first translations. So we can keep track of.

**Comment by janmenzel** [comment]
> > I would like to translate "React Without JSX".
> 
> Cool (: I'll add you. Could you please open a PR after your first translations? So we can keep track of it.

Sure thing.

**Comment by codejet** [comment]
I could take "Reconciliation" now.

**Comment by tamarau** [comment]
Can I please translate ' dont-call-proptypes'?

**Comment by miku86** [comment]
> Can I please translate ' dont-call-proptypes'?

Thanks for your help, @tamarau , I added you.

Please make sure, that you do not translate the message itself.

> These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). **People tend to search these, so please don't translate the error message itself.**

**Comment by tamarau** [comment]
Can I please do 'Context' please?

**Comment by miku86** [comment]
> Can I please do 'Context' please?

Thanks @tamarau, you've been added.

**Comment by mhienle** [comment]
Can I do "Styling and CSS" please?

**Comment by miku86** [comment]
> Can I do "Styling and CSS" please?

Thanks @mhienle, just added you.

**Comment by mhienle** [comment]
I could also do "Babel, JSX, and Build Steps" and "Component State" soon. :slightly_smiling_face:

**Comment by michaelneu** [comment]
I'd like to do the warnings, if that's ok. I've already submitted #94 for review 🙂

**Comment by electrovagance** [comment]
Hi all, I would love to contribute.  If possible, I would like to start with the FAQ page.  If that's okay, feel free to assign the translation of "APIs and AJAX" to me.

**Comment by rwachtler** [comment]
Hi! I'd take **Error Boundaries** (https://reactjs.org/docs/error-boundaries.html) 🙂

**Comment by amelieoller** [comment]
I'd like to work on "File Structure" (https://reactjs.org/docs/faq-structure.html) from the FAQs if that's alright.

**Comment by amelieoller** [comment]
Happy to do another one, "Uncontrolled Components" (https://reactjs.org/docs/uncontrolled-components.html) from the "Advanced Guides".

**Comment by amelieoller** [comment]
Time for another one :) I can do "React Without ES6" from the "Advanced Guides".

**Comment by rwachtler** [comment]
Since **Error Boundaries** is in review (#108). I would like to continue with **Forwarding Refs** (https://reactjs.org/docs/forwarding-refs.html).

**Comment by rwachtler** [comment]
@ph1p 

> Please take only one page at a time.
This rule applies only until the PR for the current translation is open right?

If yes, I'd like to continue with **Fragments** (https://reactjs.org/docs/fragments.html).

**Comment by ph1p** [comment]
I translated it already @rwachtler

**Comment by ph1p** [comment]
Adde you @rwachtler and thanks for your PRs! I try to check them as soon as possible.

**Comment by wogsland** [comment]
I'm going to submit a PR of the unknown-prop warning translation.

**Comment by wogsland** [comment]
I'm going to submit a PR of the `refs-must-have-owner` warning translation.

**Comment by codejet** [comment]
I could take "Web Components" now

**Comment by codejet** [comment]
looks like web components was already translated 😅

**Comment by codejet** [comment]
instead i could take "Typechecking With PropTypes" and "Strict Mode"

**Comment by ZweiDM** [comment]
> instead i could take "Typechecking With PropTypes" and "Strict Mode"

I translated already "Typechecking With PropTypes". I will make a PR by tomorrow.

**Comment by Tamiira** [comment]
I could translate "Portals" ->  https://de.reactjs.org/docs/portals.html

**Comment by miku86** [comment]
> > instead i could take "Typechecking With PropTypes" and "Strict Mode"
> 
> I translated already "Typechecking With PropTypes". Can I be linked for a PR? :)

@ZweiDM

Thanks for your interest in making a contribution.
I will mark you for this `Typechecking With PropTypes`.
Please open a pull request.

For the next time, please report here first.
This will ensure that no issues are translated twice,
what could lead to disappointment and trouble.

**Comment by miku86** [comment]
> instead i could take "Typechecking With PropTypes" and "Strict Mode"

@codejet 

Thanks,
I **added you** for `Strict Mode`.

`Typechecking With PropTypes` is **already taken**.

**Comment by miku86** [comment]
> I could translate "Portals" -> [de.reactjs.org/docs/portals.html](https://de.reactjs.org/docs/portals.html)

@Tamiira 

Thank you for your interest in making a contribution.
I **added you** for `Portals`.

**Comment by ZweiDM** [comment]
> For the next time, please report here first.
> This will ensure that no issues are translated twice,
> what could lead to disappointment and trouble.

Thank you, for letting me do this contribution.
Next time I will ask for it, before I do it! :)
 
You can find the **PR** for `Typechecking With PropTypes` here: #113

**Comment by timhoffmannGIThub** [comment]
Hi, would love to translate the render-props!

**Comment by miku86** [comment]
@timhoffmannGIThub 

Thanks for your interest in making a contribution.
I **added you** for `Render Props`.

**Comment by Tamiira** [comment]
Just submitted the PR for `Portals` here: #121  :)

**Comment by wogsland** [comment]
I'm going to submit a PR for the "Refs and the DOM" Guide.

**Comment by wogsland** [comment]
I'm going to submit a PR for the "React Without ES6" guide.

**Comment by wogsland** [comment]
I'm going to submit a PR for the "Integrating with Other Libraries" guide.

**Comment by timhoffmannGIThub** [comment]
Submitted the PR for render props here: #120

**Comment by r3sMetz** [comment]
I'd like to go on with "JSX In Depth"

**Comment by ph1p** [comment]
> I'd like to go on with "JSX In Depth"

Sure! I added you

**Comment by rwachtler** [comment]
I'd like to take _Hooks at a Glance_  🙂

**Comment by pmaier983** [comment]
Hello, Id like to take `Passing Functions to Components` (https://de.reactjs.org/docs/faq-functions.html) 1/4 done and hope to finish it next weekend. Can open a draft if needed.

**Comment by ph1p** [comment]
Hi @pmaier983, sure! :)

**Comment by timidak** [comment]
Hi folks, do you still need help with the translation? I would love to help. 😁

**Comment by ph1p** [comment]
> Hi folks, do you still need help with the translation? I would love to help. 😁

Hello! Sure :) just choose a topic you want to translate and I will add you to the list.

**Comment by timidak** [comment]
> > Hi folks, do you still need help with the translation? I would love to help. 😁
> 
> Hello! Sure :) just choose a topic you want to translate and I will add you to the list.

Alright, I would like to translate `Building Your Own Hooks`. Is there a deadline? I would guess it will take me like two weeks from now. 😄

**Comment by ph1p** [comment]
No there is no deadline. Take your time. Please create a PR so that we can keep an overview or help you, if you've problems.

**Comment by liza-kl** [comment]
Hi, I'd like to work on the Core Page "Tutorial" is that still possible?

**Comment by ph1p** [comment]
Hi @liza-kl ! Sure! There is already a PR open with a "help wanted" label: https://github.com/reactjs/de.reactjs.org/pull/34 simply fork and extend it (:

**Comment by vincentrohde** [comment]
Hi, I would like to translate "Using the Effect Hook" `/docs/hooks-effect`. Is that still available?

**Comment by ph1p** [comment]
@vincentrohde Yes, it is available. I will add you :)

**Comment by Serag114** [comment]
Hi, I would like to translate "How to Contribute"!

**Comment by ph1p** [comment]
Sure @Serag114 , just create a PR. I'll add you! Thanks :)

**Comment by mnlfischer** [comment]
Please add me to Versioning Policy. I will translate it.

**Comment by ph1p** [comment]
@mnlfischer sure :) thank you!

**Comment by PReichetanz** [comment]
Hi, I would like to translate `Hooks API Reference`. Is it still available?

**Comment by michael-schantin** [comment]
Hi, I would like to translate the "Test-Umgebungen" page.

**Comment by ph1p** [comment]
Thanks @michael-schantin I will add you :)

**Comment by ph1p** [comment]
> Beim Lesen des Kapitels _Hauptkonzepte_ fällt auf, dass es auf den Seiten noch diverse Rechtschreibfehler gibt. Ich habe diese mit Hilfe von cSpell Korrektur gelesen und zunächst lokal verbessert. Auch wurde scheinbar die deutsche Version von MDN zu einer Premium Version verändert und ist nicht mehr ohne Weiteres der Allgemeinheit zugänglich (siehe [hier](https://hacks.mozilla.org/2022/04/mdn-plus-now-available-in-more-markets/)). Ich schlage vor, die verbleibenden Links auf deutschen Seiten (beginnend mit https://developer.mozilla.org/de) zurück auf die englischen Versionen zu setzen. Ich kann dies in einem eigenen Branch übernehmen, wenn gewünscht.
> 
> When reading the _Main Concepts_ chapter, you will notice that there are still various spelling mistakes on the pages. I proofread them with the help of cSpell and improved them locally first. The German version of MDN has also apparently been changed to a premium version and is no longer readily available to the general public (see [here](https://hacks.mozilla.org/2022/04/mdn-plus-now-available-in-more-markets/)). I suggest reverting the remaining links to German pages (starting with https://developer.mozilla.org/de) back to the English versions. I can do this in a separate branch if you want.

I looked it up and it doesn't say that the German documentation is only available with MDN-Plus (https://developer.mozilla.org/en-US/plus#subscribe).

However, I noticed that the German language has been disabled (https://github.com/orgs/mdn/discussions/147). So it is a good suggestion to set everything to the English version :) 

Feel always free to open a PR

**Comment by michael-schantin** [comment]
I'll take test recipes as the next page.

**Comment by michael-schantin** [comment]
For the sake of completeness, I'll translate the Profiler page next.

**Comment by michael-schantin** [comment]
There are still some untranslated parts in the React Top-Level API chapter. I take care of it.

**Comment by marvhock** [comment]
Hi, I would like to translate this page: Hooks FAQ (https://de.reactjs.org/docs/hooks-faq.html).

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
I created an issue for the new website translation: https://github.com/reactjs/de.react.dev/issues/317
